# Generated by Django 4.2.7 on 2024-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='po_freight_amt_amt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_packaging_forwording_amt_amt',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
