# Generated by Django 4.2.7 on 2024-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase_order_po_freight_amt_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_received_notes',
            name='grn_freight_percentage_amt_amt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='goods_received_notes',
            name='grn_packaging_forwording_amt_amt',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
