# Generated by Django 4.2.7 on 2024-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goods_received_notes_grn_freight_percentage_amt_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='so_shipping_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
