# Generated by Django 4.2.7 on 2024-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sales_order_so_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_notes',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
