# Generated by Django 4.2.7 on 2024-08-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_credit_notes_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_notes',
            name='custom_id',
        ),
    ]
