# Generated by Django 4.2.7 on 2024-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_credit_notes_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_received',
            name='payment_received_bank_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
