# Generated by Django 4.2.7 on 2024-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_received_payment_received_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_voucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cash_voucher',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
