# Generated by Django 4.2.7 on 2024-08-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cash_voucher_amount_alter_cash_voucher_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_voucher',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cash_voucher',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
