# Generated by Django 4.2.7 on 2024-09-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cash_voucher_amount_alter_cash_voucher_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order',
            name='so_order_confirmation_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
