# Generated by Django 4.2.7 on 2024-09-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sales_order_so_order_confirmation_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='godown',
            new_name='godown_name_old',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.godown'),
        ),
    ]
