# Generated by Django 4.2.7 on 2024-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_godown_inventory_godown_name_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_challan',
            name='dc_Dispatch_document_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
