# Generated by Django 4.2.7 on 2024-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delivery_challan_dc_dispatch_document_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inv_Dispatch_document_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
