# Generated by Django 4.2.7 on 2024-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invoice_inv_dispatch_document_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa_invoice',
            name='inv_Dispatch_document_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
