# Generated by Django 4.2.7 on 2024-10-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_performa_invoice_inv_dispatch_document_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_challan',
            name='dc_Dispatch_document_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='inv_Dispatch_document_no',
        ),
    ]
