# Generated by Django 4.2.7 on 2024-10-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_delivery_challan_dc_dispatch_document_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='po_coc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_delivery',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_payment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_test_certificate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_warranty_certificate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
