# Generated by Django 4.2.7 on 2024-10-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_purchase_order_po_coc_purchase_order_po_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='po_quo_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_quotation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
