# Generated by Django 4.2.7 on 2024-10-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_purchase_order_po_quo_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa_invoice',
            name='invoice_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
    ]
