# Generated by Django 4.2.7 on 2024-10-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_performa_invoice_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa_invoice',
            name='invoice_shipping_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
