# Generated by Django 4.2.7 on 2024-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_performa_invoice_invoice_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='po_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
