"""
Django settings for epiphanycrm project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os, logging,sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=nsz30rb(^cmxl836rv^eg2-sseutvcvb9ui2%u7sqn=c3lxfc'
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'epiphanycrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'epiphanycrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'keymech',
        'USER':'root',
        'PASSWORD':'password',
        'HOST':'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

SESSION_SAVE_EVERY_REQUEST = True
 
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds, increase as needed
 
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
 
TIME_ZONE = 'Asia/Kolkata'
 
USE_I18N = True
 
USE_TZ = True
###################################################################################### 
#STATIC_URL = '/static_keymech/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = '/home/Mech_Front_Keymech/mechfront-keymech/Mechfront_tech/static/'
#STATIC_URL = '/static_keymech/'

#MEDIA_URL = '/media_keymech/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Static files
#STATIC_URL = '/static_keymech/'
#STATIC_ROOT = '/home/Mech_Front_Keymech/mechfront-keymech/staticfiles_collected/'

# Media files
#MEDIA_URL = '/media_keymech/'
#MEDIA_ROOT = '/home/Mech_Front_Keymech/mechfront-keymech/media/'
 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static_keymech/'
STATIC_ROOT = '/home/keymech/Mechfront_tech/static/'

MEDIA_URL = '/media_keymech/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CSRF_TRUSTED_ORIGINS = [
    'https://app2.olatechs.com',
]
#MEDIA_URL = '/media/'

#STATIC_URL="/static/"
#STATIC_ROOT=os.path.join(BASE_DIR,"staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
